# dinocvLib AMAZON-II º¸µå Static Library Makefile

CROSS_COMPILE 	= #ae32000-elf-uclibc-

AS		= $(CROSS_COMPILE)as
LD		= $(CROSS_COMPILE)ld
CC		= $(CROSS_COMPILE)gcc
CPP		= $(CROSS_COMPILE)g++
AR		= $(CROSS_COMPILE)ar
NM		= $(CROSS_COMPILE)nm
STRIP	= $(CROSS_COMPILE)strip
OBJCOPY	= $(CROSS_COMPILE)objcopy
OBJDUMP	= $(CROSS_COMPILE)objdump
RANLIB	= $(CROSS_COMPILE)ranlib
ELF2FLT	= $(CROSS_COMPILE)elf2flt
STRIP		= $(CROSS_COMPILE)strip

CFLAGS	= -O2 -Wall -Dlinux -D__linux__ -Dunix -D__uClinux__ -DEMBED

COMPILER_PREFIX=/usr/local/ae32000-elf-uclibc-tools
LDFLAGS = -r -Xlinker -T$(COMPILER_PREFIX)/lib/ae32000-elf2flt.ld
LDFLAGS_DBG = -Xlinker -T$(COMPILER_PREFIX)/lib/ae32000-elf2flt.ld

LDLIBS	= -lm -lc -lpthread


LIB_SRCS = dinocore/imgcore.cpp\
dinocore/bmpanal.cpp\
dinocore/imgdraw.cpp\
dinocore/imgconv.cpp\
dinocore/ppmanal.cpp\
dinocore/imageio.cpp\
dinods/ds_sort.cpp\
dinods/linkedlist.cpp\
dinods/queue.cpp\
dinoproc/binarization.cpp\
dinoproc/dp.cpp\
dinoproc/filter.cpp\
dinoproc/cannyedge.cpp\
dinoproc/chaincode.cpp\
dinoproc/convexhull.cpp\
dinoproc/labeling.cpp\
dinoproc/feature.cpp\
dinoproc/histogram.cpp\
dinoproc/morphology.cpp\
dinoproc/resize.cpp\
dinoproc/thinning.cpp\
dinomm/memmgr.cpp

LIB_OBJS = $(LIB_SRCS:.cpp=.o)
LIB_HDRS = $(LIB_SRCS:.cpp=.h)

OUTPUT_PATH = /usr/local/lib/
DINOCVLIB = $(OUTPUT_PATH)libdinocv.a

export AS LD CC CPP AR NM STRIP OBJCOPY OBJDUMP RANLIB CFLAGS




all: $(DINOCVLIB)

$(DINOCVLIB): $(LIB_OBJS)

	$(AR) ruv $(DINOCVLIB) $(LIB_OBJS)

.cpp.o:
	$(CPP) $(CFLAGS) -c $< -o $@

.s.o:
	$(AS) $< -o $@
	

clean:
	rm -f dinocore/*.o dinoproc/*.o dinods/*.o dinomm/*.o $(DINOCVLIB)
